name: Build Shigu Docker Image
on: 
  #每次master发生推送就会运行一次
  push:
    branches: [master]
jobs: 
  docker_build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build And Push Docker Image
        env:
          image_name: choate1990/shigu_robot
          tag: melodic-ros-desktop-full
        run: |
          docker version
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
          cd shigu-robot/desktop-full
          docker build -t $image_name:$tag .
          docker push $image_name:$tag
      