name: Build and Test Shigu Docker Image
on: 
  #每次master发生推送就会运行一次
  push:
    branches: 
      - master
    tags:
      - all
jobs: 
  docker_build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build And Push Melodic Docker Image
        env:
          image_name: choate1990/shigu_robot
          tag: melodic-ros-desktop-full
        run: |
          docker version
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
          cd shigu-robot/melodic-desktop-full
          docker build -t $image_name:$tag . --no-cache
          docker push $image_name:$tag
      # - name: Build And Push Noetic Docker Image
      #   env: 
      #     image_name: choate1990/shigu_robot
      #     tag: noetic-ros-desktop-full
      #   run: |
      #     docker version
      #     docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      #     cd shigu-robot/melodic-desktop-full
      #     docker build -t $image_name:$tag . --no-cache
      #     docker push $image_name:$tag
  regression_test:
    runs-on: ubuntu-latest
    container:  choate1990/shigu_robot:melodic-ros-desktop-full
    needs:
      - docker_build
    shell: bash
    steps:
      - name: Regression Test available_data_test
        run: | 
          cd /root/Shigu/
          source devel/setup.bash
          rostest shigu_gazebo available_data_test.test
      - name: Regression Test unavailable_data_test
        run: | 
          cd /root/Shigu/
          source devel/setup.bash
          rostest shigu_gazebo unavailable_data_test.test