name: Build and Test Shigu Docker Image
on: 
  tags:
    - all
jobs: 
  docker_build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build And Push Melodic Docker Image
        env:
          image_name: choate1990/shigu_robot
          tag: melodic-ros-desktop-full
        run: |
          docker version
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
          cd shigu-robot/melodic-desktop-full
          docker build -t $image_name:$tag . --no-cache
          docker push $image_name:$tag
      # - name: Build And Push Noetic Docker Image
      #   env: 
      #     image_name: choate1990/shigu_robot
      #     tag: noetic-ros-desktop-full
      #   run: |
      #     docker version
      #     docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      #     cd shigu-robot/melodic-desktop-full
      #     docker build -t $image_name:$tag . --no-cache
      #     docker push $image_name:$tag
  regression_test:
    runs-on: ubuntu-latest
    container: choate1990/shigu_robot:melodic-ros-desktop-full
    needs:
      - docker_build
    steps:
      - name: Regression Test 
        shell: bash
        run: |
          cd /root/Shigu && source /root/Shigu/devel/setup.bash && catkin_make run_tests