name: Build and Test Shigu Docker Image
on: 
  push:
    tags:
      - test
jobs: 
  regression_test:
    runs-on: ubuntu-latest
    container: choate1990/shigu_robot:melodic-ros-desktop-full
    steps:
      - name: Regression Test 
        shell: bash
        run: |
          cd /root/Shigu && source /root/Shigu/devel/setup.bash && catkin_make run_tests