name: Test Shigu Function
on: 
  #每次master发生推送就会运行一次
  push:
    branches: 
      - master
    tags:
      - only_test

jobs: 
  regression_test:
    runs-on: ubuntu-latest
    container:  choate1990/shigu_robot:melodic-ros-desktop-full
    needs:
      - docker_build
    shell: bash
    steps:
      - name: Regression Test available_data_test
        run: | 
          cd /root/Shigu/
          source devel/setup.bash
          rostest shigu_gazebo available_data_test.test
      - name: Regression Test unavailable_data_test
        run: | 
          cd /root/Shigu/
          source devel/setup.bash
          rostest shigu_gazebo unavailable_data_test.test